# Generated by Django 2.2.3 on 2019-07-13 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='suppliertype',
            options={'verbose_name': 'supplier type', 'verbose_name_plural': 'suppliers types'},
        ),
        migrations.AddField(
            model_name='supplier',
            name='status',
            field=models.CharField(choices=[('RESEARCH', 'поиск информации'), ('VALID', 'все в порядке'), ('UNCLEAR', 'подозрительный клинет')], default='RESEARCH', max_length=64),
        ),
        migrations.AlterField(
            model_name='suppliertype',
            name='criteria',
            field=models.ManyToManyField(blank=True, to='criteria.Criterion'),
        ),
    ]
