# Generated by Django 2.2.3 on 2019-07-13 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0002_auto_20190713_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='tender',
            name='buyer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='suppliers.Supplier', verbose_name='buyer'),
        ),
    ]
