# Generated by Django 2.2.3 on 2019-07-13 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0004_tendermember_tender'),
    ]

    operations = [
        migrations.AddField(
            model_name='tender',
            name='winner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='win_tenders', to='suppliers.Supplier'),
        ),
        migrations.AlterField(
            model_name='tender',
            name='buyer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tenders', to='suppliers.Supplier', verbose_name='buyer'),
        ),
    ]
