# Generated by Django 2.2.3 on 2019-07-13 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('criteria', '0002_auto_20190713_2205'),
        ('suppliers', '0005_auto_20190713_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tender',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='win_tenders', to='suppliers.Supplier'),
        ),
        migrations.CreateModel(
            name='SupplierCheckResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='criteria.Criterion')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suppliers.Supplier')),
            ],
            options={
                'verbose_name': 'check result',
                'verbose_name_plural': 'check results',
                'unique_together': {('supplier', 'criterion')},
            },
        ),
    ]
