# Generated by Django 2.2.3 on 2019-07-13 17:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0007_auto_20190714_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vote',
            name='criterion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='criteria.Criterion'),
        ),
    ]
