version: '3'

services:
  digital_backend:
    build:
      context: .
      dockerfile: ./compose/app/Dockerfile
    env_file:
      - ./.env
    volumes:
      - app_logs:/application/logs
      - app_static:/application/static
      - app_media:/application/media
    links:
      - redis
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:11-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_backups:/backups
    env_file:
      - ./.env

  redis:
    image: redis:latest
    expose:
      - "6379"
    restart: always

  rabbitmq:
    image: rabbitmq:3.7-alpine
    expose:
      - "5672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  nginx:
    build:
      context: .
      dockerfile: ./compose/nginx/Dockerfile
    expose:
      - "80"
    ports:
      - "80:80"
    volumes:
      - app_static:/application/static
      - app_media:/application/media
    depends_on:
      - digital_backend


volumes:
  app_static:
  app_logs:
  app_media:
  postgres_data:
  postgres_backups:
  rabbitmq_data:
