# Generated by Django 2.2.3 on 2019-07-13 12:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('criteria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='criterion',
            name='machine_name',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.AddField(
            model_name='criterion',
            name='weight',
            field=models.FloatField(default=1),
        ),
    ]
