# Generated by Django 2.2.3 on 2019-07-13 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('criteria', '0002_auto_20190713_2205'),
    ]

    operations = [
        migrations.RenameField(
            model_name='criterion',
            old_name='machine_name',
            new_name='uuid',
        ),
    ]
